# Generated by Django 4.2.7 on 2025-06-29 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_profile_files_alter_profile_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='files',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sales',
        ),
    ]
